export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const STORE_ARTICLES = 'STORE_ARTICLES';
export const ARTICLES_LOADING = 'ARTICLES_LOADING';
export const ARTICLES_LOAD_COMPLETE = 'ARTICLES_LOAD_COMPLETE';
export const ARTICLES_LOAD_FAILED = 'ARTICLES_LOADED';
