export default [
  { key: 'us', name: 'United States of America' },
  { key: 'ae', name: 'United Arab Emirates' },
  { key: 'ar', name: 'Argentina' },
  { key: 'at', name: 'Austria' },
  { key: 'au', name: 'Australia' },
  { key: 'be', name: 'Belgium' },
  { key: 'bg', name: 'Bulgaria' },
  { key: 'br', name: 'Brazil' },
  { key: 'ca', name: 'Canada' },
  { key: 'ch', name: 'Switzerland' },
  { key: 'cn', name: 'China' },
  // { key: 'co', name: '' },
  // { key: 'cu', name: '' },
  // { key: 'cz', name: '' },
  // { key: 'de', name: '' },
  // { key: 'eg', name: '' },
  // { key: 'fr', name: '' },
  { key: 'gb', name: 'United Kingdom of Great Britain' }
  // { key: 'gr', name: '' },
  // { key: 'hk', name: '' },
  // { key: 'hu', name: '' },
  // { key: 'id', name: '' },
  // { key: 'ie', name: '' },
  // { key: 'il', name: '' },
  // { key: 'in', name: '' },
  // { key: 'it', name: '' },
  // { key: 'jp', name: '' },
  // { key: 'kr', name: '' },
  // { key: 'lt', name: '' },
  // { key: 'lv', name: '' },
  // { key: 'ma', name: '' },
  // { key: 'mx', name: '' },
  // { key: 'my', name: '' },
  // { key: 'ng', name: '' },
  // { key: 'nl', name: '' },
  // { key: 'no', name: '' },
  // { key: 'nz', name: '' },
  // { key: 'ph', name: '' },
  // { key: 'pl', name: '' },
  // { key: 'pt', name: '' },
  // { key: 'ro', name: '' },
  // { key: 'rs', name: '' },
  // { key: 'ru', name: '' },
  // { key: 'sa', name: '' },
  // { key: 'se', name: '' },
  // { key: 'sg', name: '' },
  // { key: 'si', name: '' },
  // { key: 'sk', name: '' },
  // { key: 'th', name: '' },
  // { key: 'tr', name: '' },
  // { key: 'tw', name: '' },
  // { key: 'ua', name: '' },
  // { key: 've', name: '' },
  // { key: 'za', name: '' }
];
